language: node_js

os:
  - windows
  - linux
  - osx

node_js:
  - 14 # lts

cache:
  yarn: true

# needed for windows travis, which gets stuck after running tests
# https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288/9
env:
  - YARN_GPG=no

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH
  - export CI=true

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc

deploy:
  skip_cleanup: true
  provider: script
  script: npx pleb publish
  on:
    branch: master
    node_js: 14
    condition: $TRAVIS_OS_NAME = linux
