language: node_js

os:
  - windows
  - linux
  - osx

node_js:
  - 14 # lts

cache:
  yarn: true

# needed for windows travis, which gets stuck after running tests
# https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288/9
env:
  - YARN_GPG=no

# Travis uses yarn@1.3.2 on linux, and yarn@latest on other platforms.
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH
  - export CI=true

# Install lerna-publisher pacakge that will manage pubishing and configure npm to use proper credentials
before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc

# lerna-publisher publish will publish all uppublished versions in your monorepo
deploy:
  skip_cleanup: true
  provider: script
  script: npx pleb publish
  on:
    os: linux
    node: 14
    branch: master
    # Disabled because of 3 tags limitation https://developer.github.com/v3/activity/events/types/#createevent 
    # tags: true
