import { writeFile as w, readdir as r, readFile as rf } from 'fs';
import watch from 'node-watch';
import { promisify } from 'util';
import { normalize } from 'path';
const writeFile = promisify(w);
const readdir = promisify(r);
const readFile = promisify(rf);

const examples = 'src/examples';
const toString = async (content: Promise<string>) => {
    try {
        return JSON.stringify(await content);
    } catch (e) {
        return `'' // not found`;
    }
};
const safeRead = async (path: string) => {
    try {
        return await readFile(normalize(`${examples}/${path}`), { encoding: 'utf8' });
    } catch (e) {
        return `'' // not found`;
    }
}
const updateIndex = async (_event?: string, filePath?: string) => {
    if (filePath === normalize(`${examples}/index.ts`)) {
        return;
    }
    const dirs = (await readdir(examples, { withFileTypes: true })).
        filter(dir => dir.isDirectory()).
        map(i => i.name);
    const sources = dirs.map(d => safeRead(`${d}/source.tsx`));
    const compiled = dirs.map(d => safeRead(`${d}/compiled.ts`));
    const styles = dirs.map(d => safeRead(`${d}/style.css`));

    const imports = dirs.
        map((example, index) => `import { runExample as run${index} } from './${example}/compiled';`);
    const exports = dirs.map(async (dir, index) =>
        `{
    name:'${dir}', 
    run: run${index},
    source: ${await toString(sources[index])},
    compiled: ${await toString(compiled[index])},
    style: ${await toString(styles[index])}
}`);
    writeFile(normalize(`${examples}/index.ts`),
        `// Generated by example-playground/src/utils/watch-examples.ts

${imports.join('\n')}

export default [${(await Promise.all(exports)).join(',\n\t')}] as Example[];

export interface Example {
    run: (target:HTMLElement) => () => void;
    name: string;
    source: string;
    compiled: string;
    style: string;
}`);
};

updateIndex().then(() => {
    watch(normalize(`${examples}/`), { recursive: true, persistent: true }, updateIndex);
});
